const { promises: fs } = require("fs");

const msInOneDay = 1000 * 60 * 60 * 24;

const today = new Date();
const quote = {
  2: "“What great thing would you attempt, if you knew you could not fail.”  –  Robert H. Schuller",
  3: "“It’s not about money or connections.  It’s the willingness to outwork and outlearn everyone when it comes to your business.”  –  Mark Cuban",
  4: "“Success is not final; failure is not fatal; it is the courage to continue that counts.”  –  Winston Churchill",
  5: "“Don’t stop when you’re tired. Stop when you’re done.”  –  Wesley Snipes",
  6: "“Shoot for the moon. Even if you miss, you’ll land among the stars.”  –  Norman Vincent Peale",
  7: "“The journey of a thousand miles begins with one step.”  –  Lao Tzu",
  8: "“Act as if what you do makes a difference.”  IT DOES.”  –  William James",
  9: "“Always take another step. If this is to no avail take another, and yet another. One step at a time is not too difficult.”  –  Og Mandino",
  10: "“If you can’t fly, then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do, you have to keep moving forward.” – Martin Luther King, Jr.",
  11: "“Much effort, much prosperity.”  –  Euripides",
  12: "“Your true success in life begins only when you make the commitment to become excellent at what you do.”  –  Brian Tracy",
  13: "“Much good work is lost for the lack of a little more.”  –  Edward H. Harriman",
  14: "“Your biggest failure is the thing you dreamed of contributing but didn’t find the guts to do.”  –  Seth Godin",
  15: "“That some achieve great success, is proof to all that others can achieve it as well.”  –  Abraham Lincoln",
  16: "“Never let the fear of striking out get in your way.”  –  Babe Ruth",
  17: "“Hustle until you no longer need to introduce yourself.”  –  Anonymous",
  18: "“The heights by great men reached and kept, were not attained by sudden flight, but they, while their companions slept, were toiling upward in the night.”  –  Henry Wadsworth Longfellow",
  19: "“He who would accomplish little must sacrifice little; he who would achieve much must sacrifice much.”  –  James Allen",
  20: "“If you wish to be out front, then act as if you were behind.”  –  Lao Tzu",
  21: "“The key to success is failure.” – Michael Jordan",
  22: "“Formula for success: rise early, work hard, strike oil.”  –  J. Paul Getty",
  23: "“Plough deep while sluggards sleep.”  –  Benjamin Franklin",
  24: "“Work hard in silence and let success be your noise.”  –  Anonymous",
  25: "“Don’t stop until you’re proud.”  –  Anonymous",
  26: "“The path to success is to take massive, determined action.” – Tony Robbins",
  27: "“If it’s important, you’ll find a way.  If it’s not, you’ll find an excuse.”  –  Ryan Blair",
  28: "“Men of action are favored by the goddess of good luck.”  –  George S. Clason",
  29: "“A somebody was once a nobody who wanted to and did.”  –  John Burroughs",
  30: "“Man cannot discover new oceans unless he has the courage to lose sight of the shore.”  –  Andre Gide",
  31: "“If you believe you can do a thing, you can do it.”  –  Claude M. Bristol",
  32: "“Action is the foundational key to all success.”  –  Pablo Picasso",
  33: "“Thought allied fearlessly to purpose becomes creative force.”  –  James Allen",
  34: "“Run your own race. Who cares what others are doing? The only question that matters is, am I progressing?”  –  Robin Sharma",
  35: "“There’s not a person on my team in 16 years that has consistently beat me to the ball every play. That ain’t got anything to do with talent, that’s just got everything to do with effort, and nothing else.”  –  Ray Lewis",
  36: "“Don’t watch the clock; do what it does. Keep going.”  –  Sam Levonson",
  37: "“Winners embrace hard work. They love the discipline of it, the trade-off they’re making to win. Losers, on the other hand, see it as a punishment.And that’s the difference.”  –  Lou Holtz",
  38: "“Push yourself, because no one else is going to do it for you.” – Anonymous",
  39: "“Life shrinks or expands in proportion to one’s courage.”  –  Anais Nin",
  40: "“Nothing in this world is worth having or worth doing unless it means effort, pain, difficulty.”  –  Theodore Roosevelt",
  41: "“In this world you only get what you grab for.” – Giovanni Boccaccio",
  42: "“Success means having the courage, the determination, and the will to become the person you believe you were meant to be.”  –  George A. Sheehan",
  43: "“The best way to predict the future is to create it.”  –  Peter Drucker",
  44: "“If you have everything seems under control, you’re just not going fast enough.”  –  Mario Andretti",
  45: "“Do the work. Everyone wants to be successful, but nobody wants to do the work.”  –  Gary Vaynerchuk",
  46: "“Be so good they can’t ignore you.”  –  Steve Martin",
  47: "“Be not afraid of going slowly; be afraid only of standing still.”  –  Chinese Proverb",
  48: "“When we strive to become better than we are, everything around us becomes better too.”  –  Paulo Coelho",
  49: "“With self-discipline, most anything is possible.”  –  Theodore Roosevelt",
  50: "“All the so-called ‘secrets of success’ will not work unless you do.” – Anonymous",
  51: "“Your dreams are on the other side of your grit.”  –  Anonymous",
  52: "“Courage is being scared to death…and saddling up anyway.”  –  John Wayne",
  53: "“Some succeed because they are destined to, but most succeed because they are determined to.”  –  Henry Van Dyke",
  54: "“What you exhibit outwardly, you are inwardly.”  –  Claude M. Bristol",
  55: "“If you continue to thin the way you’ve always thought, you’ll continue to get what you’ve always got.”  –  Kevin Trudeau",
  56: "“They indeed are fools who are satisfied with the fruits of their past effort and do not engage themselves in self-effort now.”  –  Swami Venkatesananda",
  57: "“Dreams are not what you see in your sleep, they are the things that don’t let you sleep.”  –   Cristiano Ronaldo",
  58: "“I CAN is 100 times more important that IQ.”  –  Anonymous",
  59: "“It is better to fail in originality than to succeed in imitation.”  –  Herman Melville",
  60: "“Opportunities don’t happen. You create them.”  –  Chris Grosser",
  61: "“Don’t be afraid to give up the good to go for the great.”  –  John D. Rockefeller",
  62: "Success is dependent on effort.”  –  Sophocles",
  63: "“Good, better, best. Never let it rest. ‘Till your good is better and your better is best.'”  –  St. Jerome",
  64: "“Winning is not everything, but the effort to win is.”  –  Zig Ziglar",
  65: "“How long should you try? Until.”  –  Jim Rohn",
  66: "“The view is better when it is earned.”  –  Anonymous",
  67: "“You have power over your mind, not outside events. Realize this, and you will find strength.”  –  Marcus Aurelius",
  68: "“Keep your eyes on the stars, and your feet on the ground.”  –  Theodore Roosevelt",
  69: "“Courage is fear holding on a minute longer.”  –  George S. Patton",
  70: "“Surround yourself with people who are only going to lift you higher.”  –  Anonymous",
  71: "“Comfort is the enemy of progress.” – P.T. Barnum",
  72: "“Stop chasing the money and start chasing the passion.”  –  Tony Hsieh",
  73: "“If you are not willing to risk the usual, you will have to settle for the ordinary.”   –  Jim Rohn",
  74: "“All progress takes place outside the comfort zone.”  –  Michael John Bobak",
  75: "“Greatness is succeeding at what you intend to do.”  –  Dr. Joe Vitale",
  76: "“Don’t let the fear of losing be greater than the excitement of winning.”  –  Robert Kiyosaki",
  77: "“Work your ass off. There is no magic pill.” – Arnold Schwarzenegger",
  78: "“If you really look closely, most overnight successes took a long time.”  –  Steve Jobs",
  79: "“Success is not for the lazy.”  –  Anonymous",
  80: "“All good ideas start out as bad ideas, that’s why it takes so long.”  –  Steven Spielberg",
  81: "“If you don’t play to win, don’t play at all.”  –  Tom Brady",
  82: "“You must tell yourself; “No matter how hard it is, or how hard it gets, I’M GOING TO MAKE IT!'”  –  Les Brown",
  83: "“Remember that guy that gave up? Neither does anyone else.”  –  Anonymous",
  84: "“For us, there is only the trying. The rest is not our business.” – T.S. Eliot",
  85: "“I hated ever minute of training, but I said, “Don’t quit. Suffer now and live the rest of your  life as a champion.”  –  Muhammad Ali",
  86: "“When I was young, I observed that nine out of ten things I did were failures. So I did ten times more work.”  –  George Bernard Shaw",
  87: "“The only limit to our realization of tomorrow will be our doubts of today.” – Franklin D. Roosevelt",
  88: "“Success doesn’t just happen. You have to be intentional about it, and that takes discipline.”  –  John C. Maxwell",
  89: "“Believe you can and you’re halfway there.”  –  Theodore Roosevelt",
  90: "“It was desire that brought progress to the world.”  –  Claude M. Bristol",
  91: "“The secret to happiness is freedom… and the secret to freedom is courage.”  –  Thucydides",
  92: "“The way to get started is to quit talking and begin doing.”  –  Walt Disney",
  93: "“The successful warrior is the average man, with laser-like focus.”  –  Bruce Lee",
  94: "“There are no secrets to success. It is the result of preparation, hard work, and learning from failure.”  –  Colin Powell",
  95: "“Satisfaction lies in the effort, not in the attainment, full effort is full victory.”  –  Mahatma Gandhi",
  96: "“Give your dreams all you’ve got and you’ll be amazed at the energy that comes out of you.”  –  William James",
  97: "“The artist is nothing without the gift, but the gift is nothing without work.”  –  Emile Zola",
  98: "“There is no failure except in no longer trying.”  –  Elbert Hubbard",
  99: "“Don’t you dare let their laughter extinguish your ambition.”  –  J.K. Rowling",
  100: "“Continuous Effort, not strength or intelligence, is the key to unlocking our potential.”  –  Winston Churchill",
  101: "“If you can dream it, you can do it.”  –  Walt Disney",
  102: "“He who is not courageous enough to take risks will accomplish nothing in life.”  –  Muhammad Ali",
  103: "“In any given moment, we have two options: To step forward into growth or to step back into safety.”  –  Abraham Maslow",
  104: "“Strength and growth come only through continuous effort and struggle.” – Napoleon Hill",
  105: "“It takes courage to grow up and become who you really are.”  –  E.E. Cummings",
  106: "“You don’t lose if you get knocked down; you lose if you stay down.”  –  Muhammad Ali",
  107: "“Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.”  –  Conrad Hilton",
  108: "“It’s going to be hard, but hard does not mean impossible.”  –  Anonymous",
  109: "“Some people dream of success while others wake up and work.”  –  Anonymous",
  110: "“Always discover your vision and the rest will follow.”  –  Arnold Schwarzenegger",
  111: "“You have to think big to be big.”  –  Claude M. Bristol",
  112: "“Sometimes, things may not go your way, but the effort should be thereevery single night.”  –  Michael Jordan",
  113: "“Perseverance is the hard work you do after you get tired of doingthe hard work you already did.”  –  Newt Gingrich",
  114: "“You know you are on the road to success if you would do your job, and not be paid for it.”  –  Oprah Winfrey",
  115: "“Effort is only effort when it begins to hurt.”  –  Jose Ortega y Gassett",
  116: "“Even if you’re on the right track, you’ll get run over if you just sit there.”  –  Will Rogers",
  117: "“Things may come to those who wait, but only the things left by those who hustle.”  –  Abraham Lincoln",
  118: "“A person without a goal is like a ship without a rudder.”  –  Thomas Carlyle",
  119: "“Life is so much more rewarding if you strive for something, rather than take what’s given to you on a plate.” – Amy Winehouse",
  120: "“To anyone who is struggling early in the morning or late at night in pursuit of your dream, struggles that many will never see, and to any leaders out there, who believe in someone who does not yet believe in themselves, keep going. Keep going, because WILL always finds a WAY.”  –  Tom Brady",
  121: "“If your dreams don’t scare you, they aren’t big enough.”  –  Muhammad Ali",
  122: "“Why live an ordinary life, when you can live an extraordinary one.”  –  Tony Robbins",
  123: "“In all human affairs there are efforts, and there are results, and the strengthof the effort is the measure of the result.”  –  James Allen",
  124: "“Most successful people are the most successful people because they’ve failed more than anyone else.”  –  Tony Robbins",
  125: "“You deserve what your actions earned, or haven’t earned.”  –  M.J. Demarco",
  126: "“If you hesitate, some bolder hand will stretch out before you and get the prize.”  –  P.T. Barnum",
  127: "“A lot of people say they want to be great, but they’re not willing to make the sacrifices necessary to achieve greatness.”  –  Kobe Bryant",
  128: "“Greatness is not measured by what a man or woman accomplishes, but by the opposition they overcame to reach their goals.”  –  D. Height",
  129: "“There are simply no limits for a person who accepts no limits.”  –  Robin Sharma",
  130: "“I will persist until I succeed. I was not delivered into this world in defeat, nor does failure course in my veins. I am not a sheep waiting to be prodded by my shepherd. I am a lion and I refuse to talk, to walk, to sleep with the sheep. The slaughterhouse of failure is not my destiny. I will persist until I succeed.”  –  Og Mandino",
  131: "“I failed my way to success.” –  Thomas Edison",
  132: "“There’s nothing like biting off more than you can chew, and then chewing anyway.”  –  Mark Burnett",
  133: "“Success comes from knowing that you did your best to become the best that you are capable of becoming.”  –  John Wooden",
  134: "“We must do our work for its own sake, not for fortune or attention or applause.”  –  Steven Pressfield",
  135: "“I know the price of success; dedication, hard work and an unremitting devotion to the things you want to see happen.”  –  Frank Lloyd Wright",
  136: "“One painful duty fulfilled makes the next plainer and easier.”  –  Hellen Keller",
  137: "“Don’t be pushed around by the fears in your mind.  Be led by the dreams in your heart.”  –  Roy T. Bennett",
  138: "“Never give up on something you can’t go a day without thinking about.”  –  Winston Churchill",
  139: "“It is time to reverse this prejudice against conscious effort and to see the powers we gain through practice and discipline as eminently inspiring and even miraculous.”  –  Robert Greene",
  140: "“Education comes from within; you get it by struggle and effort and thought.”  –  Napoleon Hill",
  141: "“To live is to learn, to strive is to become.” – Friedrich Nietzsche",
  142: "“Success is nothing more than a few simple disciplines, practiced every day.”  –  Jim Rohn",
  143: "“Do not bite at the bait of pleasure till you know there is no hook beneath it.”  –  Thomas Jefferson",
  144: "“The only man who doesn’t make mistakes is the man who never does anything.”  –  Theodore Roosevelt",
  145: "“All our dreams can come true, if we have the courage to pursue them.”  –  Walt Disney",
  146: "“The devil whispers, “You can’t withstand the storm.” The Warrior replied, “I am the storm.”  –  Anonymous",
  147: "“To win you’ve got to stay in the game.”  –  Claude M. Bristol",
  148: "“The size of your success is measured by the strength of your desire, the size of your dream, and how you handle disappointment along the way.”  –  Robert Kiyosaki",
  149: "“Always make a total effort, even when the odds are against you.”  –  Arnold Palmer",
  150: "“I’ve failed over and over and over again in my life – and that is why I succeed.”  –  Michael Jordan",
  151: "“Tough time don’t last.  Tough people do.”  –  Robert H. Schuller",
  152: "“There will be obstacles. There will be doubters. There will be mistakes.  But with hard work, there are no limits.”  –  Michael Phelps",
  153: "“Once you agree upon the price you and your family must pay for success, it enables you to ignore the minor hurts, the opponent’s pressure, and the temporary failures.”  –  Vince Lombardi",
  154: "“Valor grows by daring; fear by holding back.”  –  Publilius Syrus",
  155: "“Eighty percent of success is showing up.”  –  Woody Allen",
  156: "“Success is the progressive realization of a worthy goal.”  –  Earl Nightingale",
  157: "“Unwearied ceaseless effort is the price that must be paid for turning faith into a rich infallible experience.”  –  Mahatma Gandhi",
  158: "“Never give up, for that is just the place and time that the tide will turn.”  –  Harriet Beecher Stowe",
  159: "“If you want to have more, you must become more.”  –  Jim Rohn",
  160: "“For success, attitude is equally as important as ability.”  –  Walter Scott",
  161: "“There are no limits to what you can accomplish, except the limits you place on your own thinking.”  –  Brian Tracy",
  162: "“It’s the constant and determined effort that breaks down all resistance,sweeps away all obstacles.”  –  Claude M. Bristol",
  163: "“The difference between ordinary and extraordinary is that little extra.”  –  Jimmy Johnson",
  164: "“God doesn’t require us to succeed, he only requires that you try.”  –  Mother Teresa",
  165: "“Enthusiasm is the mother of effort, and without it nothing great was everachieved.”  –  Ralph Waldo Emerson",
  166: "“We don’t have to be smarter than the rest; we have to be more disciplinedthan the rest.”  –  Warren Buffett",
  167: "“Inaction breeds doubt and fear. Action breeds confidence and courage. Ifyou want to conquer fear, do not sit home and think about it. Go out andget busy.”  –  Dale Carnegie",
  168: "“People are rewarded in public for what they’ve practiced for years in private.”  –  Tony Robbins",
  169: "“Our greatest glory is not in never failing, but in rising up every time we fail.”  –  Ralph Waldo Emerson",
  170: "“Motivation gets you going, but discipline keeps you growing.”  –  John C. Maxwell",
  171: "“Never confuse a single defeat with a final defeat.”  –  F. Scott Fitzgerald",
  172: "“I planned my success, I knew it was going to happen.”  –  Erykah Badu",
  173: "“Only put off until tomorrow what you are willing to die having left undone.”  –  Pablo Picasso",
  174: "“If you had one shot, or one opportunity, to seize everything you ever wanted, in one moment, would you capture it? Or just let it slip?”  –  Eminem",
  175: "“Effort is grossly underrated.”  –  Gary Vaynerchuk",
  176: "“I knew the one thing I might regret was not ever having tried.”  –  Jeff Bezos",
  177: "“Successful and unsuccessful people do not vary greatly in their abilities.  They vary in their desires to reach their potential.”  –  John Maxwell",
  178: "“He who sweats more in training bleeds less in war.”  –  Spartan Creed",
  179: "“You can, end of story.”  –  Ray Lewis",
  180: "“It does not matter how slowly you go as long as you do not stop.”  –  Confucius",
  181: "“The harder you work, the harder it is for you to surrender.”  –  Vince Lombardi",
  182: "“Problems are only opportunities in work clothes.”  –  Henry J. Kaiser",
  183: "“It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult.”  –  Seneca",
  184: "“When something is important enough, you do it even if the odds are not in your favor.”  –  Elon Musk",
  186: "“When a man is sufficiently motivated, discipline will take care of itself.”  –  Albert Einstein",
  187: "“It’s never crowded along the extra mile.”  –  Wayne Dyer",
  188: "“Do a little more each day than you think you possibly can.”  –  Lowell Thomas",
  189: "“Never throughout history has a man who lived a life of ease left a name worth remembering.”  –  Theodore Roosevelt",
  190: "“No one ever defeated a resolute will. Even death stands still before such a will.”  –  Claude M. Bristol",
  191: "“You may have to fight a battle more than once to win it.”  –  Margaret Thatcher",
  192: "“Many of life’s failures are people who did not realize how close they were to success when they gave up.”  –  Thomas A. Edison",
  193: "“When everything seems to be going against you, remember that the airplane takes off against the wind, not within it.”  –  Henry Ford",
  194: "“Your daily behavior reveals your deepest beliefs.”  –  Robin Sharma",
  195: "“Aim for the highest.”  –  Andrew Carnegie",
  196: "“The price of anything is the amount of life you exchange for it.”  –  Henry David Thoreau",
  197: "“Real lions like to hunt! They like the process just as much as they love the prize.”  –  Eric Thomas",
  198: "“Inactivity is retrogression.”  –  John McDonald",
  199: "“When the end comes for you, let if find you conquering a new mountain not sliding down an old one.”  –  Jim Rohn",
  200: "“The truest wisdom is a resolute determination.”  –  Napoleon Bonaparte",
  201: "“Fate loves the fearless.”  –  James Russell Lowell",
  202: "“Whatever you can do, or dream you can, begin it. Boldness has genius, power, and magic in it.”  –  Johann Wolfgang von Goethe",
  203: "“The desire for safety stands against every great and noble enterprise.”  –  Tacitus",
  204: "“There are two mistakes one can make along the way to truth: not going all the way, and not starting.”  –  Buddha",
  205: "“What we do now echoes in eternity.”  –  Marcus Aurelius",
  206: "“Survival can be summed up in three words – never give up. That’s theheart of it really. Just keep trying.”  –  Bear Grylls",
  207: "“To believe in the heroic makes heroes.”  –  Benjamin Disraeli",
  208: "“Victory has a hundred fathers and defeat is an orphan.”  –  John F. Kennedy",
  209: "“The mark of a great man is one who knows when to set aside the important things in order to accomplish the vital ones.”  –  Brandon Sanderson",
  210: "“Do, or do not. There is no try.”  –  Yoda",
  211: "“The best revenge is massive success.”  –  Frank Sinatra",
  212: "“It always seems impossible until it’s done.”  –  Nelson Mandela",
  213: "“With the new day comes new strength and new thoughts.”  –  Elenor Roosevelt",
  214: "“You will never win if you never begin.”  –  Helen Rowland",
  215: "“Fortune favors the bold.”  –  Virgil",
  216: "“Problems are not stop signs, they are guidelines.”  –  Robert H. Schuller",
  217: "“If you fell down yesterday, stand up today.”  –  H.G. Wells",
  218: "“Set you goals high, and don’t stop till you get there.”  –  Bo Jackson",
  219: "“Change your life today.  Don’t gamble on the future, act now, without delay.”  –  Simone de Beauvoir",
  220: "“Discipline is the bridge between goals and accomplishment.”  –  Jim Rohn",
  221: "“Most people never run far enough on their first wind to find out they’ve got a second. Give your dreams all you’ve got and you’ll be amazed at the energy that comes out of you.”  –  William James",
  222: "“A winner is just a loser who tried one more time.” – George M. Moore Jr.",
  223: "“If you can’t excel with talent, triumph with effort.”  –  Dave Weinbaum",
  224: "“Persistence. The only thing that will piss-off failure enough for it to get the fu** out of the way of your success. PERSIST.”  – The Ultimate Warrior",
  225: "“The only way to do great work is to love what you do.”  –  Steve Jobs",
  226: "“A little more persistence a little more effort, and what seemed hopelessfailure may turn into a glorious success.”  –  Elbert Hubbard",
  227: "“If you put forth the effort, good things will be bestowed upon you.”  –  Michael Jordan",
  228: "“Self-discipline is the magic power that makes you virtually unstoppable.”  –  Dan Kennedy",
  229: "“Follow your dreams, they know the way.”  –  Kobe Yamada",
  230: "“No matter where you’re from, your dreams are valid.”  –  Lupita Nyong’o",
  231: "“The biggest adventure you can take is to live the life of your dreams.”  –  Opra Winfrey",
  232: "“Victory is always possible for the person who refuses defeat.” – Anonymous",
  233: "“A river cuts through a rock not because of its power, but its persistence.”  –  Anonymous",
  234: "“If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.”  –  Zig Ziglar",
  235: "“If you follow your dreams and spend your life doing what brings you joy, you are more likely to find success.” – Richard Branson",
  236: "“The people who stick with things for years and never stop almost always win the race.”  –  James Clear",
  237: "“Success is the sum of small efforts, repeated day in and day out.”  –  Robert Collier",
  238: "“What you are afraid to do is a clear indication of the next thing you need to do.”  –  Ralph Waldo Emerson",
  239: "“Get action. Seize the moment. Man was never intended to become an oyster.”  –  Theodore Roosevelt",
  240: "“Courage doesn’t always roar, sometimes it’s the quiet voice at the end ofthe day whispering ‘I will try again tomorrow’.”  –  Mary Anne Radmacher",
  241: "“Success in anything will always come down to this: Focus & Effort, andwe control both of them.”  –  Dwayne ‘The Rock’ Johnson",
  242: "“I don’t count my sit-ups, I only start counting when it starts hurting, whenI feel pain, that’s when I start counting, cause that’s when it really counts.”  –  Muhammad Ali",
  243: "“It doesn’t matter whether you are pursuing success in business, sports, thearts, or life in general: The bridge between wishing and accomplishing is discipline.”  –  Harvey Mackay",
  244: "“The greatest test of courage on the earth is to bear defeat without losingheart.”  –  R.G. Ingersoll",
  245: "“Only those who dare to fail greatly can ever achieve greatly.”  –  Robert F. Kennedy",
  246: "“He who seeks rest finds boredom….He who seeks work finds rest.”  –  Anonymous",
  247: "“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.”  –  Earl Nightingale",
  248: "“The man who succeeds is a man who has withstood the tests of time, trials,and has made every effort count.”  –  Hermann J. Steinherr",
  249: "“We are all self-made, but only the successful will admit it.”  –  Earl Nightingale",
  250: "“Make each day count by setting specific goals to succeed, then putting forth every effort to exceed your own expectations.”  –  Les Brown",
  251: "“We all have dreams. But in order to make dreams come into reality, it takesan awful lot of determination, dedication, self-discipline, and effort.”  –  Jesse Owens",
  252: "“Our greatest glory is not in never falling but in rising every time we fall.”  –  Confucius",
  253: "“It’s not that I’m so smart, it’s just that I stay with problems longer.”  –  Albert Einstein",
  254: "“Opportunities are usually disguised as hard work, so most people don’t recognize them.”  –  Ann Landers",
  255: "“To follow, without halt, one aim: There’s the secret of success.”  –  Anna Pavlova",
  256: "“In the confrontation between the stream and the rock, the stream alwayswins – not through strength, but through persistence.”  –  Buddha",
  257: "“Kites rise highest against the wind – not with it.”  –  Winston Churchill",
  258: "“A man’s life is interesting primarily when he has failed. I well know. For its a sign that he tried to surpass himself.”  –  Georges Clemenceau",
  259: "“Climb mountains not so the world can see you, but so you can see the world.”  –  David McCullough Jr.",
  260: "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.”  –  Vince Lombardi",
  261: "“Persistence is to the character of man as carbon is to steel.”  –  Napoleon Hill",
  262: "“Energy and persistence conquer all things.”  –  Benjamin Franklin",
  263: "“Anything is possible if you’ve got enough nerve.”  –  J.K. Rowling",
  264: "“The best way out is always through.”  –  Robert Frost",
  265: "“No great achievement is possible without persistent work.”  –  Bertrand Russell",
  266: "“Permanence, perseverance, and persistence in spite of all obstacles, discouragement, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak.”  –  Thomas Carlyle",
  267: "“What you believe yourself to be, you are.”  –  Claude M. Bristol",
  268: "“If you are going through hell, keep going.”  –  Winston Churchill",
  269: "“To uncover your true potential, you must first find your own limits and then you have to have the courage to blow past them.”  –  Picabo Street",
  270: "“Life is being on the wire, everything else is just waiting.”  –  Karl Wallenda",
  271: "“Success doesn’t come to you, you go to it.”  –  T. Scott Mcleod",
  272: "“Glory gives herself only to those who have always dreamed of her.”  –  Charles de Gaul",
  273: "“If you believe it will work out, you’ll see opportunities. If you believe it won’t, you will see obstacles.”  –  Wayne Dyer",
  274: "“Be Fearless in the pursuit of what sets your soul on fire.”  –  Anonymous",
  275: "“Never say never, because limits, like fears, are often just an illusion.”  –  Michael Jordan",
  276: "“The level path is easy, but it will not bring you to the mountaintop.”  –  Dr. Idel Dreimer",
  277: "“Whatever the mind of man can conceive and believe, it can achieve.”  –  Napoleon Hill",
  279: "“If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.”  –  James Cameron",
  280: "“To be successful we must do things that unsuccessful people do not wantto do. Those things require levels of courage.”  –  R. Harpe",
  281: "“He who is firm in will molds the world to himself.”  –  Johann Wolfgang von Goethe",
  282: "“The sight of an achievement is the greatest gift that a human being could offer to others.”  –  Ayn Rand",
  283: "“Where I excel, is ridiculous, sickening, work-ethic!”  –  Will Smith",
  284: "“It’s never too late to be what you might have been.”  –  George Elliot",
  285: "“Do not wait to strike till the iron is hot: But make it hot by striking.”  –  William B. Sprague",
  286: "“Nothing is impossible, the word itself says “I’m possible.”  –  Audrey Hepburn",
  287: "“Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.”  –  Dale Carnegie",
  288: "“It is during our darkest moments that we must focus to see the light.”  –  Aristotle Onassis",
  289: "“I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.”  –  Jimmy Dean",
  290: "“I am not a product of my circumstances. I am a product of my decision.”  –  Stephen Covey",
  291: "“The most common way people give up their power is by thinking they don’t have any.”  –  Alice Walker",
  292: "“The most difficult thing is the decision to act, the rest is merely tenacity.”  –  Amelia Earhart",
  293: "“Whether you think you can or you think you can’t, you’re right.”  –  Henry Ford",
  294: "“You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.” – George Lorimer",
  295: "“Build your own dreams, or someone else will hire you to build theirs.”  –  Farrah Gray",
  296: "“You can’t use up creativity. The more you use, the more you have.”  –  Maya Angelou",
  297: "“Don’t judge each day by the harvest you reap but by the seeds that you plant.”  –  Robert Louis Stevenson",
  298: "“I would rather die of passion than of boredom.”  –  Vincent van Gogh",
  299: "“Life is like riding a bicycle. To keep your balance, you must keep moving.”  –  Albert Einstein",
  300: "“I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.”  –  Leonardo da Vinci",
  301: "“Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.”   –  Jamie Paolinetti",
  302: "“If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.”  –  Sheryl Sandberg",
  303: "“Life isn’t about finding yourself. Life is about creating yourself.” – George Bernard Shaw",
  304: "“If you want to make an easy job seem mighty hard, just keep putting off doing it.”  –  Olin Miller",
  305: "“What we achieve inwardly will change outer reality.”  –  Plutarch",
  306: "“Follow effective actions with quiet reflection. From the quiet reflection will come even more effective action.”  –  Peter Drucker",
  307: "“You have to learn the rules of the game. And then you have to play better than anyone else.”  –  Albert Einstein",
  308: "“Amateurs sit and wait for inspiration, the rest of us just get up and go to work.”  –  Stephen King",
  309: "“I alone cannot change the world, but I can cast a stone across the water to create many ripples.” – Mother Teresa",
  310: "“The secret of success in life is for a man to be ready for his opportunity when it comes.”  –  Benjamin Disraeli",
  311: "“Don’t brood. Get on with living and loving. You don’t have forever.”  –  Leo Buscaglia",
  312: "“You do what you can for as long as you can, and when you can’t, you do the next best thing. You back up, but you don’t give up.”  –  Chuck Yeager",
  313: "“Change your thoughts and you change your world.”  –  Norman Vincent Peale",
  314: "“The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.”  –  Mark Caine",
  315: "“For success, attitude is equally as important as ability.”  –  Harry F. Banks",
  316: "“The world is full of educated derelicts. Perseverance and determination alone are omnipotent.”  –  Calvin Coolidge",
  317: "“Judge your success by what you had to give up in order to get it.”  –  Dalai Lama",
  318: "“Your work is to discover your world and then with all your heart give yourself to it.”  –  Buddha",
  319: "“Live as if you were to die tomorrow. Learn as if you were to live forever.”  –  Mahatma Gandhi",
  320: "“Success is largely a matter of holding on after others have let go.”  –  Anonymous",
  321: "“Your attitude, not your aptitude, will determine your altitude.”  –  Zig Ziglar",
  322: "“Nothing is less productive than to make more efficient what should not bedone at all.”  –  Peter Drucker",
  323: "“Success is how high you bounce when you hit bottom.”  –  George S. Patton",
  324: "“Ambition is the path to success. Persistence is the vehicle you arrive in”  –  Bill Bradley",
  325: "“Before anything else, preparation is the key to success.”  –  Alexander Graham Bell",
  326: "“If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.”  –  Jim Rohn",
  327: "“Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.”  –  Harriet Tubman",
  328: "“Striving for success without hard work is like trying to harvest where youhaven’t planted.”  –  David Bly",
  329: "“Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.” – Anonymous",
  330: "“I am grinding while your sleeping.”  –  Gary Vaynerchuk",
  331: "“Our greatest fear should not be of failure … but of succeeding at things inlife that don’t really matter.”  –  Francis Chan",
  332: "“Criticism is the price of Ambition.”  –  Robin Sharma",
  333: "“The road to success is always under construction.”  –  Lily Tomlin",
  334: "“Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.”  –  Bo Bennett",
  335: "“Every strike brings me closer to the next home run.”  –  Babe Ruth",
  336: "“The three great essentials to achieve anything worthwhile are, first, hardwork; second, stick-to-itiveness; third, common sense.” – Thomas Edison",
  337: "“Put a grain of boldness into everything you do.”  –  Baltasar Gracian",
  338: "“Light tomorrow with today.”  –  Elizabeth Barrett Browning",
  339: "“Keep your face always toward the sunshine—and shadows will fall behind you.”  –  Walt Whitman",
  340: "“Be brave. Take risks. Nothing can substitute experience.”  –  Paulo Coelho",
  341: "“You can never achieve more than you aspire to.”  –  Al Ries",
  342: "“Don’t fear failure. — Not failure, but low aim, is the crime. In great attempts it is glorious even to fail.”  –  Bruce Lee",
  343: "“Every master was once a disaster.”  –  T. Harv Eker",
  344: "“When you play, play hard; when you work, don’t play at all.”  –  Theodore Roosevelt",
  345: "“Nothing is worth more than this day.”  –  Johann Wolfgang von Goethe",
  346: "“When people don’t believe in you, you have to believe in yourself.”  –  Peirce Brosnan",
  347: "“Ordinary is easy. Extra-ordinary is what will separate you from the crowd.”  –  Darren Hardy",
  348: "“Sometimes adversity is what you need to face in order to become successful.”  –  Zig Ziglar",
  349: "“Take time to deliberate; but when the time for action arrives, stop thinking and go in.”  –  Napoleon Bonaparte",
  350: "“To be a champ you have to believe in yourself when no one else will.” –  Sugar Ray Robinson",
  351: "“To dare is to lose one’s footing momentarily. To not dare is to lose oneself.”  –  Soren Kierkegaard",
  352: "“I believe every human has a finite number of heartbeats. I don’t intend to waste any of mine.”  –  Neil Armstrong",
  353: "“When you cease to dream you cease to live.”  –  Malcom Forbes",
  354: "“Paralyze resistance with persistence.”  –  Woody Hayes",
  355: "“Winning means… you’re willing to go longer, work harder, give more than anyone else.”  –   Vince Lombardi",
  356: "“We are made to persist. That’s how we find out who we are.”  –  Tobias Wolff",
  357: "“Patience, persistence, and perspiration make an unbeatable combination for success.”  –  Napoleon Hill",
  358: "“When you want to succeed as bad as you want to breathe, then you’ll be successful.”  –  Eric Thomas",
  359: "“Money grows on the tree of persistence.”  –  Japanese Proverb",
  360: "“Nothing in this world can take the place of persistence. Talent will not:nothing is more common than unsuccessful men with talent.”  –  Calvin Coolidge",
  361: "“Champions keep playing until they get it right.”  –  Billy Jean King",
  362: "“As long as there’s breath in You–Persist!  –  Bernard Kelvin Clive",
  363: "“Sometimes a winner is just a dreamer who just won’t quit.” – Rudy",
  364: "“Press on. Nothing in the world can take the place of persistence.”  –  Ray Kroc",
  365: "“The pessimist complains about the wind;   the optimist expects it to change;   the realist adjusts the sails.”  –  William Arthur Ward",
  366: "“It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all — in which case, you fail by default.”  –  J.K. Rowling",
  367: "“Obstacles are those frightful things you see when you take your eyes off your goals.”  –  Henry Ford",
  368: "“What most of us never suspect of existing, is the silent but irresistiblepower which comes to the rescue of those who fight on in the face ofdiscouragement.” – Napoleon Hill",
  376: "“Grit is living life like it is a marathon,  not a sprint.”  –  Angela Duckworth",
  377: "“Grit is having the courage to push through, no matter what the obstacles are, because it’s worth it.”  –  Chris Morris",
  378: "“Success doesn’t just happen.  It is a product of hard work, grit and ingenuity.”  –  Ogwo David Eminike",
  379: "Grit is sticking with your future day in, day out and not just for the week, not just for the month, but for years.”  –  Angela Duckworth",
  380: "“Consistency of effort over the long run is everything.”  –  Angela Duckworth",
  381: "“Great works are performed not by strength, but by perseverance.”  –  Samuel Johnson",
  382: "“True grit is making a decision and standing by it, doing what must be done.  No moral man can have peace of mind if he leaves undone what he knows he should have done.”  –  John Wayne",
  383: "“True grit is staying in the game when others would have dropped the ball and left the park.”  –  Anonymous",
  384: "“A dream doesn’t become reality through magic; it takes sweat, commitment, and hard work.”  –  Grit quote",
  385: "“The question isn’t who’s going to let me; it’s who’s going to stop me.”  –  Ayn Rand",
  386: "“You don’t need an MBA to launch a business. You need street smarts and grit.” – Barbara Corcoran",
  387: "“Grit determines that life challenges will neither defeat nor define us.”  –  Anonymous",
  388: "“Do the one thing you think you cannot do.  Fail at it.  Do better the second time.  The only people who never tumble are those who never mount the high wire.  This is your moment.  Own it.”  –  Oprah Winfrey",
  389: "“Grit depends on a different kind of hope.  It rests on the expectation that our own efforts can improve our future.”  –  Angela Duckworth",
  390: "“I don’t stop when I’m tired. I stop when I’m done.” – David Goggins",
  391: "“I remind myself that no one day of writing matters all that much.  A story is built somewhat like a stalactite — one little drop of mud and grit at a time.”  –  Joe Hill",
  392: "“Everything is hard before it is easy.”  –  Goethe",
  393: "“Grit isn’t about getting an incredible dose of inspiration or courage. It’s about building the daily habits that allow you to stick to a schedule and overcome challenges and distractions over and over and over again.”  –  James Clear",
  394: "“Don’t give up on your dreams, or your dreams will give up on you.”  –  John Wooden",
  395: "“Over time, grit is what separates fruitful lives from aimlessness.”  –  John Ortberg",
  396: "“If you are not willing to learn, no one can help you.  If you are determined to learn, no one can stop you.”  –  Zig Ziglar",
  397: "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.”  –  Vince Lombardi",
  398: "“Perseverance is the hard work you do after you get tired of doing the hard work you already did.”  –  Newt Gingrich",
  399: "“Never hope for it more than you work for it.”  –  Sonya Teclai",
  400: "“Grit is passion and perseverance for very long-term goals. Grit is having stamina.” – Angela Duckworth",
  401: "“Anything’s possible if you’ve got enough grit.”  –  Atlas Rowe",
  402: "“What is grit?  Grit is refusing to give up.  Persistence.  It’s making your own luck.”  –  Peter Diamandis",
  403: "“Someone twice as talented but half as hardworking as another person might reach the same level of skill but still produce dramatically less over time.”  –  Angela Duckworth",
  404: "“Grit is the stubborn refusal to quit.”  –  Jonah Lehrer",
  405: "“It does not matter how slowly you go as long as you do not stop.”  –  Confucius",
  406: "“Grit is the one trait that I, as a mentor, try to instill in younger entrepreneurs. Your road as an entrepreneur likely won’t be easy or straightforward. But, fortunately, those who train themselves to persevere and remain committed to their vision and principles are much more likely to attain their entrepreneurial goals than those who lack this sense of grit.”  –  Amine Rahal",
  407: "“You can have all the talent in the world, but you will never achieve your goals without effort. This is why grit is the foundation of success.”  –  Ashley Elizabeth",
  408: "“Nothing is put on pause. Everything is still happening. And then as far as just reflecting on what got you to where you are, there aren’t very many times where we have the space to sit and reflect and really understand the depth of what it took and the grit that we had to have to get to where we are.” – Jessica Alba",
  409: "“Grit comes down to your habits. It’s about doing the things you know you’re supposed to do on a more consistent basis. It’s about your dedication to daily practice and your ability to stick to a schedule.” – James Clear",
  410: "“Sometimes, a winner is a dreamer who just won’t quit.”  –  Rudy",
  411: "“It is after all, the dab of grit that seeps into an oyster’s shell that makes the pearl, not pear-making seminars with other oysters.”  –  Stephen King",
  412: "“The moment you feel like quitting is the time you need to keep on going.  Persistence fuels genius.  And grit creates champions.”  –  Robin Sharma",
  413: "“Quitting is the easiest thing to do.”  –  Robert Kiyosaki",
  414: "“The #1 predictor of success… Grit!  The ability to persevere, overcome and move forward in spite of challenges, failures and obstacles.”  –  Anonymous",
  415: "“Our potential is one thing.  What we do with it is quite another.”  –  Angela Duckworth",
  416: "“Gritty people are resilient, in the sense that they thrive through adversity. They reframe every challenge as an opportunity and do the work to become the master of their emotions.”  –  Ashley Elizabeth",
  417: "“It’s not that I am so smart; it’s just that I stay with problems longer.”  –  Albert Einstein",
  418: "“God honors a beautiful blend of gift and grit! He gives the gift, and He expects us to have the grit to practice and learn how to use it effectively.”  –  Beth Moore",
  419: "“The difference in winning and losing is most often…  Not quitting.”  –  Walt Disney",
  420: "“Dreams don’t work unless you do.”  –  John C. Maxwell",
  421: "“Grit is not just simple elbow-grease term for rugged persistence. It is an often invisible display of endurance that lets you stay in an uncomfortable place, work hard to improve upon a given interest, and do it again and again.”  –  Sarah Lewis",
  422: "“A champion is someone who gets up when he can’t.”  –  Jack Dempsey",
  423: "“When a goal matters enough to a person, that person will find a way to accomplish what at first seemed impossible.” – Nido Qubein",
  424: "“I hated every minute of training, but I said don’t quit.  Suffer now and live the rest of your life as a champion.”  –  Muhammad Ali",
  425: "“Only those who will risk going too far can possibly find out how far one can go.”  –  T.S. Eliot",
  426: "“Most of the important things in the world have been accomplished by people who have kept on trying when there seemed no hope at all.”  –  Dale Carnegie",
  427: "“Dream chasing is not for the faint of heart. Not only does it take massive courage to reach for the dreams and goals that many shrug off as impossible, but it also takes grit, tenacity, and an indomitable spirit to see things through.”  –  Nathan Lee Morales",
  428: "“A little more persistence a little more effort, and what seemed hopelessfailure may turn into a glorious success.” – Elbert Hubbard",
  429: "“Leadership grit begets grit. Lead by example.”  –  Bill Hybels",
  430: "“Grit is the persistence in following your own destiny.”  –  Paul Bradley Smith",
  431: "“Grit is not synonymous with hard work. It involves a certain single-mindedness. An ungritty prison inmate will mount a daring new escape attempt every month, but a gritty prison inmate will tunnel his way out one spoonful of concrete at a time. Grit.”  –  Chip Heath",
  432: "“Every great story happened when someone decided not to give up.”  –  Spryte Loriano",
  433: "“A leader should have higher grit and tenacity, and be able to endure what the employees can’t.”  –  Jack Ma",
  434: "“To be gritty is to fall down seven times and rise eight.”  –  Angela Duckworth",
  435: "“Grit; a mixture of hard work, consistency, and hustle.”  –  Anonymous",
  436: "“Listen, every overnight success has taken 15 years, and that’s just the way it goes.” – Daymond John",
  437: "“The 99% that achieve are willing to sacrifice, be persistent and put in disproportionate work, and think in 50 year terms not 50 day terms.” – Gary Vaynerchuk",
  438: "“One step at a time.  One punch at a time.  One round at a time.”  –  Rocky Balboa",
  439: "“There isn’t a person anywhere who isn’t capable of doing more than he thinks he can.”  –  Henry Ford",
  440: "“To be gritty is to keep working when others would have given up.”  –  Angela Duckworth",
  441: "“For great things do not just happen by impulse, but are a succession of small things linked together.” – Vincent Van Gogh",
  442: "“Effort is one of those things that gives meaning to life. Effort means you care about something, that something is important to you and you are willing to work for it.”  –  Carol Dweck",
  443: "Grit, determination, the right amount of crazy, self belief – everything it takes to be a champion. I have that.”  –  Dustin Poirier",
  444: "“No matter how much falls on us, we keep plowing ahead. That’s the only way to keep the roads clear.”  –   Greg Kincaid",
  445: "“Grit is choosing to hang on when you desperately want to let go.”  –  The STRIVE",
  446: "“Grit is guts, resilience, industriousness and tenacity.  Grit is the ability to focus, stay determined, stay optimistic in the face of a challenge, and simply work harder than the next guy or gal.”  –  Linda Kaplan Thaler",
  447: "“Grit is the grain of character. It may generally be described as heroism materialized, spirit and will thrust into heart, brain, and backbone, so as to form part of the physical substance of the man.”  –  Edwin Percy Whipple",
  448: "“Mental dominance is what ultimately makes you unstoppable.” – Tim S. Grover",
  449: "“It’s hard to beat a person who never gives up.” – Babe Ruth",
  450: "“Grit is that ‘extra something’ that separates the most successful people from the rest.” – Travis Bradberry",
  451: "“Grit is more endurance than strength. Grit is about working on something you care about so much that you’re willing to see it through to completion.” – Lee David Daniels",
  452: "“To achieve a different result simply requires a different choice of understanding, grit and intention.” – Ty Howard",
  453: "“Strength does not come from physical capacity.  It comes from an indomitable will.”  –  Mahatma Gandhi",
  454: "“There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.” – Michael Phelps",
  455: "“Enthusiasm is common. Endurance is rare.” – Angela Duckworth",
  456: "“Talent counts.  But effort counts twice.”  –  Tom Bilyeu",
  457: "“The most successful people are those who are willing to keep moving forward after making mistakes.  They find a way not to avoid life’s inevitable obstacles, but to overcome them.”  –  Ashley Elizabeth",
  458: "“When we demonstrate grit or are described as gritty, it is because we have had the resilience to push ourselves over, through, around, and sometimes under obstacles.”  –  Kori D. Miller",
  459: "“People that have grit are extraordinarily resilient and are willing to put in the effort to get things done.”  –  Lee David Daniels",
  460: "“Grit is a super power. Intelligence is awesome, but the ability to push through the emotional firestorm that is failure will take you anywhere you want to go. There are plenty of intelligent people that never do anything with their lives. But the gritty among us rule the world.” – Tom Bilyeu",
  461: "“The people who achieve success are the ones with grit, determination, and guts.” – Russell Brunson",
  462: "“If grit begins with passion, you need to know what you’re interested in, and more importantly, what you love.  And you need to be clear about what you want now.”  –  Brendon Burchard",
  463: "“I walk slowly, but I never walk backward.” – Abraham Lincoln",
  464: "“If you surround yourself with gritty people who are mentally tough and psychologically resilient, it will positively influence your own attitude and behavior.”  –  Shade Zahrai",
  465: "“At the end of the day, success is about resilience and grit.”  –  Andy Frisella",
  466: "“Luck has nothing to do with it, I have spent many, many hours, countless hours, on the court working for my one moment in time, not knowing when it would come.”  –  Serena Williams",
  467: "“The only way out is through.”  –  Helen Keller",
  468: "“The harder the conflict, the greater the triumph.”  –  George Washington",
  469: "“If you don’t give up, you still have a chance. Giving up is the greatest failure.”  –  Jack Ma",
  470: "“Grit is the stubborn refusal to quit.”  –  Grit Quote",
  471: "“It’s not over till I win.”  –  Les Brown",
  472: "“Grit is about staying committed to your goals, even when it’s hard.”   –  Angela Duckworth",
  473: "“Long is the way and hard, that out of hell leads up to the light.”  –  John Milton",
  474: "“Success is the ability to go from one failure to another with no loss of enthusiasm.” – Winston Churchill",
  475: "“The greatest predictor of success is grit.”  –  Angel Duckworth",
  482: "“Most of the reasons we don’t do things is because we’re afraid to fail.  I just made a decision one day that I was not going to do things in my life because of fear.”  –  Sara Blakely",
  483: "“Instead of failure being the outcome, failure became not trying. And it forced me at a young age to want to push myself so much further out of my comfort zone.”  –  Sara Blakely",
  484: "“When something I cant’ control happens, I ask myself; where is the hidden gift?  Where is the positive in this?”  –  Sara Blakely",
  485: "“Don’t be intimidated by what you don’t know.  That can be your greatest strength and ensure that you do things differently from everyone else.”  –  Sara Blakely",
  486: "“Failure is not the outcome.  Failure is not trying.”  –  Sara Blakely",
  487: "“My first account was Neiman Marcus. I cold-called them just like I had cold-called businesses when I was selling fax machines for seven years.”  –  Sara Blakely",
  488: "“You’ve got to visualize where you’re headed and be very clear about it. Take a Polaroid picture of where you’re going to be in a few years.”  –   Sara Blakely",
  489: "“Differentiate yourself!  Why are you different?  What’s important about you?  Why does the customer need you?”  –  Sara Blakely",
  490: "“There is a hidden blessing in the most traumatic things we go through in our lives.  My brain always goes to, ‘Where is the hidden blessing?  What is my gift?'”  –  Sara Blakely",
  491: "“Don’t be afraid to fail.” – Sara Blakely",
  492: "“People start businesses I think for two reasons. You can make something better that already exists, or you have an idea that doesn’t already exist. So, if you’re sitting on either one of those, you gotta go for it.” – Sara Blakely",
  493: "“Having a mental snapshot of where you are, where you are going, and what you are moving toward is incredibly powerful.”  –  Sara Blakely",
  494: "“The smartest thing I ever did was to hire my weakness.”  –  Sara Blakely",
  495: "“I knew that I wanted to start my own business.  I knew that I wanted to work for myself.  I was no stranger to the word no.  You just have to keep going.”  –  Sara Blakely",
  496: "“Trust your gut.”  –  Sara Blakely",
  497: "“Start now.  Start where you are.  Start with fear.  Start with pain.  Start with doubt.  Start with hands shaking.  Start with voice trembling.  Just start.”  –  Sara Blakely",
  498: "“My dad encouraged us to fail. Growing up, he would ask us what we failed at that week. If we didn’t have something, he would be disappointed. It changed my mindset at an early age that failure is not the outcome, failure is not trying. Don’t be afraid to fail.”  –  Sara Blakely",
  499: "“I did not have the most experience in the industry or the most money, but I cared the most.”  –  Sara Blakely",
  500: "“The thought of my mortality – I think about it a lot. I find it motivating. It can be any time that your number’s up.”  –  Sara Blakely",
  501: "“Perseverance is the key to starting a successful business.”  –  Sara Blakely",
  502: "“I think failure is nothing more than life’s way of nudging you that you are off course. My attitude to failure is not attached to the outcome, but in not trying. It is liberating. Most people attach failure to something not working out or how people perceive you. This way, it is about answering to yourself.”  –  Sara Blakely",
  503: "“Money is fun to make, fun to spend, and fun to give away.”  –  Sara Blakely",
  504: "“I ended up persevering through roadblocks by just not giving up. I used a lot of persistence balanced with humor balanced with vulnerability and I asked people to help.”  –  Sara Blakely",
  505: "“People feed off of your passion and your confidence.”  –  Sara Blakely",
  506: "“Sell the problem you’re solving, not the product.”  –  Sara Blakely",
  507: "“In starting a business and growing a business, every day is learning how to manage obstacles.”  –  Sara Blakely",
  508: "“If you don’t let knowing how it’s done intimidate you, it’s amazing what you can do.”  –  Sara Blakely",
  509: "“Work on your mindset daily because it is really going to be what differentiates you between other entrepreneurs.”  –  Sara Blakely",
  510: "“When you’re doing something and your purpose is greater than yourself, it will give you courage you never knew you had.”  –  Sara Blakely",
  511: "“Ensure that you do things differently from everyone else.”  –  Sara Blakely",
  512: "“I always say, ‘I think being a woman in business is our weakness and strength are being underestimated.” – Sara Blakely",
  513: "“I’d never worked in fashion or retail. I just needed an undergarment that didn’t exist.”  –  Sara Blakely",
  514: "“You’ve got to embrace what you don’t know.”  –  Sara Blakely",
  515: "“I think very early on in life we all learn what we’re good at and what we’re not good at, and we stay where it’s safe.”  –  Sara Blakely",
  516: "“When you help a woman fulfill her potential, magic happens.”  –  Sara Blakely",
  517: "“Trying new things and not being afraid to fail along the way are more important than what you learn in school.”  –  Sara Blakely",
  518: "“Resilience is like a muscle. The more you get through something and not let it get you down or defeat you, the stronger your resilience muscle becomes.”  –  Sara Blakely",
  525: "“Many will start fast, few will finish strong.” – Gary Ryan Blair",
  526: "“I firmly believe that any man’s finest hour, the greatest fulfillment of all that he holds dear, is that moment when he has worked his heart out in a good cause and lies exhausted on the field of battle – victorious.” – Vince Lombardi",
  527: "“I realized the secret to success is finishing!  And not just finishing, but finishing strong!”  –  Eric Thomas",
  528: "“No matter who you are or what you do, embrace the challenge to first start with the goal to finish strong.”  –  Andy Andrews",
  529: "“It’s not where you start — It’s where you finish that counts.”  –  Zig Ziglar",
  530: "“If I fail, I try again, and again, and again. If you fail, are you going to try again? The human spirit can handle much worse than we realize. It matters how you are going to finish. Are you going to finish strong?” – Nick Vujicic",
  531: "“The last thing you want to do is finish playing or doing anything and wish you would have worked harder.”  –  Derek Jeter",
  532: "“Finish strong.  I challenge you to find two words that more absolutely define a performance objective.  For me, those two words are a clear call to action.”  –  Dan Green",
  533: "“Whatever it takes to finish things, finish. You will learn more from a glorious failure than you ever will from something you never finished.”― Neil Gaiman",
  534: "“Remember no matter how fast you run, you can’t be the winner if you don’t finish.”  –  Israelmore Ayivor",
  535: "“Great things come from hard work and perseverance. No Excuses.” – Kobe Bryant",
  536: "“It’s one thing to have the faith to get started, but it’s another thing to have the fortitude to finish strong.” – Kami Dempsey",
  537: "“You can put forth maximum effort every day of the week, but if you’re not committed to finishing strong, someone hungrier will surpass you.”  –  The STRIVE",
  538: "“One way or the other you’re going to finish… So, why not finish strong and make yourself immensely proud of your effort.”  –  Gary Ryan Blair",
  539: "“Regardless of what came before or of what is yet to come, what matters most right now is how I choose to respond to the challenge before me. Will I lie down or will I fight? The choice is mine, and I choose to FINISH STRONG.” – Dan Green",
  540: "“Stopping at third adds no more to the score than striking out. It doesn’t matter how well you start if you fail to finish.”  –  Billy Sunday",
  541: "“Start strong, stay strong, and finish strong by always remembering why you’re doing it in the first place.”  –  Ralph Marston",
  542: "“I start a picture and I finish it.”  –  Jean-Michel Basquiat",
  543: "“If the word quit is part of your vocabulary, then the word finish is likely not.”  –  B.G. Jett",
  544: "“How you finish, is what they will remember.”  –  Anonymous",
  545: "“Success seems to be connected with action.  Successful people keep moving.  They make mistakes but they don’t quit.”  –  Finish Strong Quote",
  546: "“Sometimes, a winner is a dreamer who just won’t quit.”  –  Rudy",
  547: "“Great is the art of beginning, but greater is the art of ending.”  –  Henry Wadsworth Longfellow",
  548: "“There is no room for second place. There is only one place in my game and that is first place. I have finished second twice in my time at Green Bay and I never want to finish second again.”  –  Vince Lombardi",
  549: "“Leave it all on the field.” – Allan Sepkowitz",
  550: "“You must expect great things of yourself before you can do them.”  –  Michael Jordan",
  551: "“Better is the end of a thing than its beginning, and the patient in spirit is better than the proud in spirit.”  –  Ecclesiastes 7:8",
  552: "“Chance favors those in motion.”  –  James H. Austin",
  553: "“Going in one more round when you don’t think you can. That’s what makes all the difference in your life.”  –  Rocky Balboa",
  554: "“Starting strong is good. Finishing strong is epic.” – Robin Sharma",
  555: "“One of the most important principles of success is developing the habit of going the extra mile.”  –  Napoleon Hill",
  556: "“Champions understand that finishing strong in practice, leads to finishing strong in application.  You play the way you practice.”  –  Atlas Rowe",
  557: "“Let me tell you the secret that has led me to my goal.  My strength lies solely in my tenacity.”  –  Louis Pasteur",
  558: "“Imperfect action is better than perfect inaction.”  –  Harry Truman",
  559: "“We always say, start strong, finish stronger.” – Chris Griffin",
  560: "“A little more persistence a little more effort, and what seemed hopeless failure may turn into a glorious success.” – Elbert Hubbard",
  561: "“Obstacles can’t stop you.  Problems can’t stop you.  Most of all, other people can’t stop you.  Only YOU can stop you.”  –  Jeoffrey Gitomer",
  562: "“Some people want it to happen, some wish it would happen, others make it happen.”  –  Michael Jordan",
  563: "“Circumstances are beyond human control but our conduct is in our own power.” – Benjamin Disraeli",
  564: "“The extra energy required to make another effort… is the secret of winning.”  –  Denis Waitley",
  565: "“Life’s battles don’t always go to the stronger or faster man. But sooner or later, the man who wins is the man who thinks he can.”  –  Walter D. Wintle",
  566: "“Everyone wants to be successful, but the prize eventually goes to those who strive to finish strong.  So, stay up late, do the work, and most importantly…finish strong.”  –  Atlas Rowe",
  567: "“Success in anything will always come down to this:  focus and effort, and we control both of them.”  –  Dwayne Johnson",
  568: "“Stay positive.  Work hard.  Make it happen.”  –  Finish Strong Quote",
  569: "“It’s the extra effort after you’ve done your best that creates victory.”  –  Lou Holtz",
  570: "“Finishing strong is the attitude of believing you can do something and having the courage and determination to see it through to the end.” – Brad Larsen",
  571: "“You have nothing to lose by giving your best.” – Lailah Gifty Akita",
  572: "“The best way out is always through.” – Robert Frost",
  573: "“Without ambition one starts nothing. Without work, one finishes nothing. The prize will not be sent to you. You have to win it.“  –  Ralph Waldo Emerson",
  574: "“Starting is fun, but the future belongs to finishers.” – McRae Patterson",
  575: "“Your competition is hoping you’ll take it easy today, don’t.  Finish Strong” – The Strive",
  576: "“If you believe in what you are doing, then let nothing hold you up in your work. Much of the best work of the world has been done against seeming impossibilities. The thing is to get the work done.” – Dale Carnegie",
  577: "“The person who stops studying merely because he has finished school is forever hopelessly doomed to mediocrity, no matter what may be his calling. The way of success is the way of continuous pursuit of knowledge.” – Napoleon Hill",
  578: "“Successful people make a lot of mistakes but they don’t quit.” – Conrad Hilton",
  579: "“Doing the best at this moment puts you in the best place for the next moment.”  –  Oprah Winfrey",
  580: "“Don’t tell me how hard you work. Tell me how much you get done.”  –  James Ling",
  581: "“Always do your best. What you plant now, you will harvest later.”  –  Og Mandino",
  582: "“Be true to the best you know. This is your high ideal. If you do your best, you cannot do more.”  –  H. W. Dresses",
  583: "“Set your goals high, and don’t stop till you get there.”  –  Bo Jackson",
  584: "“Don’t think about the start of the race. Think about the ending.” – Usain Bolt",
  585: "“You can’t go back and change the beginning, but you can start where you are and change the ending.”  –  C.S. Lewis",
  586: "“No one has a problem with the first mile of a journey. Even an infant could do fine for a while. But it isn’t the start that matters. It’s the finish line.” – Julien Smith",
  587: "“Not everyone who started with you will finish with you.  Be willing to go without them if you have to.”  –  Tony Gaskins",
  588: "“Nothing builds self-esteem and self-confidence like accomplishment.”  –  Thomas Carlyle",
  589: "“Ain’t nothing over till it’s over.”  –  Rocky Balboa",
  590: "“The start does matter.  The beginning is significant.  The first few steps are critical, but they aren’t the most important.  Do you know what matters more?  Do you know what makes the start look silly and easy?  The finish.”  –  Jon Acuff",
  591: "“You can’t look ahead at the finish line decide to slow down, and still expect the world to crown you a champion.”  –  Finishing Strong Saying",
  592: "“The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.” — Martin Luther King Jr.",
  593: "“The way we finish things are rarely as neat and intense as the way we start. But it’s exactly these moments, whether it is at the end of the set, or the end of a rep, where you should double down on your effort. This is when you conquer.” – Olivier Poirier-Leroy",
  594: "“It is not enough to be an enthusiastic starter; you must also be an optimistic finisher.”  –  Leon Ho",
  595: "“Most people don’t finish strong, but some do. And those that do continually get the treasures of their effort.”  –  Brian Robben",
  596: "“No one can be successful if you don’t finish what you start. Finishing strong is a sign of commitment, integrity, and excellence. Finishing strong is about choice. Each of us has the power to choose how we perform a job or a task and to finish strong.”  –  Kathyrn Kee",
  597: "“The winner of any competition always comes from among those who finish. Not from among all those who try, or all those who mean well, but from among those who face the challenge and finish, and finish strong.”  –  Brad Larsen",
  598: "“Energy and persistence conquer all things.”  –  Benjamin Franklin",
  599: "“Yesterday’s home runs don’t win today’s games.”  –  Babe Ruth",
  600: "“Nothing in the world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. Persistence and determination alone are omnipotent.”  –  Calvin Coolidge",
  601: "“It ain’t how you start out, it’s how you finish.”  –  Tony Gonzales",
  602: "“A goal is a dream with a finish line.”  –  Duke Ellington",
  603: "“What kind of competitor see’s the finish line and slows down…  Always Finish Strong.”  –  Gary Ryan Blair",
  604: "“Believe you can and you’re halfway there.”  –  Theodore Roosevelt",
  605: "“Beginnings are easy, the thing is to finish the race.”  –  Vitor Belfort",
  606: "“Think Strong.  Be Strong.  Finish Strong.”  –  Anonymous",
  607: "“Finish what you start, no matter how painful it may be.”  –  Nastia Liukin",
  608: "“Always work hard, never give up, and fight until the end because it’s never really over until the whistle blows.” – Alex Morgan",
  609: "“Most people never run far enough on their first wind to find out they’ve got a second.” – William James",
  610: "“Start strong, finish stronger.”  –  Anonymous",
  611: "“The difference between ordinary and extraordinary is that little extra.”  –  Jimmy Johnson",
  612: "“Winning isn’t imperative, but getting tougher in the fourth quarter is.”  –  Bear Bryant",
  613: "“What we call the beginning is often the end.  And to make an end is to make a beginning.  The end is where we start from.”  –  T.S. Eliot",
  614: "“You can throw in the towel, or you can use it to wipe the sweat off your face and keep going.”  –  Finish Strong Saying",
  615: "“Everybody is is pretty good in the first quarter.  Second quarter, you have a little bump or two on you coming into the half.  By the time the third quarter comes around, you’re tired, you’re laboring.  When you come to the fourth quarter, it calls on your character.”  –  Jerry Jones",
  616: "“Finishing strong is the only respectable way to finish.” — Gary Ryan Blair",
  617: "“Beginning in itself has no value, it is an end which makes beginning meaningful, we must end what we begun.”  –  Amit Kalantri",
  618: "“When you feel like quitting, think about why you started.”  –  Anonymous",
  619: "“I don’t stop when I am tired.  I stop when I am done.”  –  David Goggins",
  620: "“Get going… walk if you have to, but finish the damned race.”  –  Ron Hill",
  621: "“The world is full of starters.  Be a finisher.”  –  Anonymous",
  622: "“Courage is fear holding on a minute longer.”  –  General George S. Patton",
  623: "“Chance favors those in motion.”  –  James H. Austin",
  624: "“There are better starters than me, but I’m a strong finisher.”  –  Usain Bolt",
  625: "“The high cost of greatness is better than the low cost of mediocrity.”  –  Matshone Dhliway",
  626: "“It’s always too early too quit.”  –  Norman Vincent Peale",
  627: "“When we make progress quickly, it feeds our emotions. Then, when there’s a period of waiting or we hit a plateau, we find out how committed we really are and whether we’re going to see things through to the finish or quit.”  –  Joyce Meyer",
  628: "“It’s not luck, it’s not magic, it’s not circumstances. It’s developing a great plan and executing on it, day in and day out until the visions in your head become your reality.”  –  Andy Frisella",
  629: "“It’s not how hard you pushed along the way.  It’s having something in you to finish.”  –  Michael Jordan",
  642: "“Always remember, your focus determines your reality.”  –  George Lucas",
  643: "“It’s only after you’ve stepped outside your comfort zone that you begin to change, grow, and transform.”  –  Roy T. Bennett",
  644: "“It is those who concentrate on but one thing at a time who advance in this world. The great man or woman is the one who never steps outside his or her specialty or foolishly dissipates his or her individuality.”  –  Og Mandino",
  645: "“Ignore the noise, focus on your work.”  –  Anonymous",
  646: "“Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.”  –  Zig Ziglar",
  647: "“Don’t dwell on what went wrong. Instead, focus on what to do next. Spend your energies on moving forward toward finding the answer.” – Denis Waitley",
  648: "“Whenever you want to achieve something, keep your eyes open, concentrate and make sure you know exactly what it is you want. No one can hit their target with their eyes closed.”  –  Paulo Coelho",
  649: "“Focus on the journey, not the destination.  Joy is found not in finishing an activity but in doing it.”  –  Jack Canfield",
  650: "“Focus on the solution, not on the problem.”  –  Jim Rohn",
  651: "“What you focus on expands; results follow focus.”  –  Marcus Buckingham",
  652: "“Focus on your goal, not the how.”  –  Bob Proctor",
  653: "“Concentrate all your thoughts upon the work at hand.  The sun’s rays do not burn until brought to a focus.”  –  Alexander Graham Bell",
  654: "“Where your attention goes, your time goes”  –  Idowu Koyenikan",
  655: "“It is during our darkest moments that we must focus to see the light.”  –  Aristotle Onassis",
  656: "“Focus on simplicity…  once you get there, you can move mountains.”  –  Steve Jobs",
  657: "“What you focus on grows, what you think about expands, and what you dwell upon determines your destiny.”  –  Robin Sharma",
  658: "“Focus does not mean saying yes, it means saying no.”  –  Steve Jobs",
  659: "“You don’t get results by focusing on results.  You get results by focusing on the actions that produce results.”  –  Mike Hawkins",
  660: "“Our focus is our future, and what we focus on will multiply in our life.”  –  David DeNotaris",
  661: "“The successful warrior is the average man, with laser-like focus.”  –  Bruce Lee",
  662: "“Focus on making yourself better, not on thinking that you are better.”  –  Bodhi Sanders",
  663: "“Stay focused, go after your dreams and keep moving toward your goals.”  –  LL Cool J",
  664: "“What you focus on expands, and when you focus on the goodness in your life, you create more of it.”  –  Oprah Winfrey",
  665: "“Miserable people focus on what they hate about their life.  Happy people focus on what they love about their life.”  –  Zig Ziglar",
  666: "“Success demands singleness of purpose.”  –  Vince Lombardi",
  667: "“Starve your distractions, feed your focus.”  –  Focus Quote",
  668: "“FOCUS:  Follow One Course Until Successful.”  –  Focus Acronym",
  669: "“Stop managing your time.  Start managing your focus.”  –  Robin Sharma",
  670: "“Goals are like a map. They help us determine where we want to end up, and give us personal direction on which to focus our energy.”  –  Catherine Pulsifer",
  671: "“Your life is controlled by what you focus on.”  –  Tony Robbins",
  672: "“When walking, walk. When eating, eat.”  –  Zen Proverb",
  673: "“The key to success is to focus our conscious mind on things we desire not things we fear.”  –  Brian Tracy",
  674: "“Focus on the possibilities for success, not on the potential for failure.”  –  Napoleon Hill",
  675: "“Stay focused, ignore the distractions, and you will accomplish your goals much faster.”  –  Joel Osteen",
  676: "“Don’t focus on the pain, focus on the progress.”  –  Dwayne Johnson",
  687: "“If it’s going to make you happy, go for it –  life is short.”  –  Tiffany Darwish",
  688: "“You are destined for greatness.  Believe in yourself and Go For It!”  –  Anonymous",
  689: "“The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you can’t move forward.”  –  Steve Maraboli",
  690: "“It does not matter how slowly you go as long as you don’t stop.”  –  Confucius",
  691: "“Go for it now.  The future is promised to no one.”  –  Wayne Dyer",
  692: "“What’s done is done.  What’s gone is gone.  One of life’s lessons is always moving on.  It’s okay to look back to see how far you’ve come but keep moving forward.”  –  Roy T. Bennett",
  693: "“Just dream big. Go for it. There’s nothing holding you back. You can have ups and downs, but if you believe in something, keep the faith; keep fighting. And don’t let people put you down.”  –  Geraint Thomas",
  694: "“I live by ‘Go big or go home.’ That’s with everything. It’s like either commit and go for it or don’t do it at all.”  –  Paul Walker",
  695: "“Courage and willingness to just go for it, whether it is a conversation or a spontaneous trip or trying new things that are scary – it is a really attractive quality.”  –  Alanis Morissette",
  696: "“Good things happen when you go for it.”  –  Alan Webb",
  697: "“If you want to do something, go for it — you’ve got nothing to lose.”  –  Louis Tomlinson",
  698: "“People like to tear you down. People are always going to take shots. You’ve just got to go for it.”  –  Joan Jett",
  699: "“If you’re going through hell, keep going.”  –  Winston Churchill",
  700: "“Courage is not having the strength to go on;  it is going on when you don’t have the strength.”  –  Theodore Roosevelt",
  701: "“Whatever it is your heart desires, please go for it, it’s yours to have.”  –  Gloria Estefan",
  702: "“Even if there’s a tiny tiny chance, isn’t that worth going for it?”  –  Louis Tomlinson",
  703: "“You don’t have to see the whole staircase, just take the first step.”  –  Martin Luther King",
  704: "“I’m a big perfectionist! I’m trying to channel super-confident women like Alicia Keys, Mariah Carey and Beyonce, because I realized that if you want something, you really have to go for it, just like they do.”  –  Ariana Grande",
  705: "“I just keep putting one foot in front of the other, it stands to reason that I’m going to get there.”  –  Rachel Joyce",
  706: "“Do it now. Sometimes ‘later’ becomes ‘never.’” – Anonymous",
  707: "“Follow your passion. The rest will attend to itself. If I can do it, anybody can do it. It’s possible. And it’s your turn. So go for it. It’s never too late to become what you always wanted to be in the first place.”  –  J. Michael Straczynski",
  708: "“If people are doubting how far you can go, go so far that you can’t hear them anymore.”  –  Michele Ruiz",
  709: "“When I let go of what I am, I become what I might be.  When I let go of what I have, I receive what I need.”  –  Lao Tzu",
  710: "“Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.  And the only way to do great work is to love what you do.  If you haven’t found it yet, keep looking.  Don’t settle.  As with all matters of the heart, you’ll know when you find it.”  –  Steve Jobs",
  711: "“It is in your moments of decision that your destiny is shaped.” – Tony Robbins",
  712: "“What would happen if you gave yourself permission to do somethingyou’ve never done before? There’s only one way to find out.”  –  Gina Greenlee",
  713: "“Maybe, if you put your disbelief aside, roll up your sleeves, take some risks, and totally go for it, you’ll wake up one day and realize you’re living the kind of life you used to be jealous of.” – Jen Sincero",
  714: "“Do you want to know who you are? Don’t ask. Act! Action will delineate and define you.”  –  Thomas Jefferson",
  715: "“Yesterday is not ours to recover, but tomorrow is ours to win or lose.”  –  Lyndon B. Johnson",
  716: "“Dream big, start small, but most of all, start.”  –  Simon Sinek",
  717: "“Doing nothing gets you nothing.”  – Sean Reichle",
  718: "“You will always have ups and downs in your life and your career, but just stay positive and go for it.”  –  Angelique Kerber",
  719: "“Screw it, let’s do it — just get on with it and do it.”  –  Richard Branson",
  720: "“Do not follow where the path may lead. Go instead where there is no path and leave a trail.” – Ralph Waldo Emerson",
  721: "“Don’t wait.  The time will never be just right.”  –  Napoleon Hill",
};

function generateNewREADME() {
  const readmeContent = `
<div align="center">
<a href="https://git.io/typing-svg"><img src="https://readme-typing-svg.demolab.com?font=Fira+Code&duration=2500&pause=500&center=true&width=435&lines=Welcome+to+my+Github+%F0%9F%96%90;I'm+Mihary+Joel+ANDRIAMILANTO+;An+aspiring+software+developer" alt="Typing SVG" /></a>
</div>

<!--
<div id="header" align="center">
  <img src="https://media.giphy.com/media/hqU2KkjW5bE2v2Z7Q2/giphy.gif" width="100%"/>
</div> -->

<div id="badges" align="center">
  <a href="https://www.linkedin.com/in/mihary-jo%C3%ABl-andriamilanto-374609233/L">
    <img src="https://img.shields.io/badge/LinkedIn-blue?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn Badge"/>
  </a>
</div>

<div id="badge" align="center">
  <img src="https://komarev.com/ghpvc/?username=miharyjoe&style=flat-square&color=blue" alt=""/>
  <h1>
    hey there
    <img src="https://media.giphy.com/media/hvRJCLFzcasrR4ia7z/giphy.gif" width="30px"/>
  </h1>
</div>

<div id="quote" align="center">
  <summary>Quote of the Day</summary>
  <p>
    <#quote_of_the_day>
  </p>
</div>

<div align="center">
  <img src="https://media.giphy.com/media/dWesBcTLavkZuG35MI/giphy.gif" width="600" height="300"/>
</div>
---

### :man_technologist: About Me :

I am a Developer <img src="https://media.giphy.com/media/WUlplcMpOCEmTGBtBW/giphy.gif" width="30"> from Madagascar.

- :telescope: I’m looking for a job in web development or mobile.

- :zap: In my free time, I solve problems on codeWars, codingGame, and hackerrank. I also read tech articles.

- :mailbox: How to reach me: [![Linkedin Badge](https://img.shields.io/badge/-mihary-blue?style=flat&logo=Linkedin&logoColor=white)](https://www.linkedin.com/in/mihary-jo%C3%ABl-andriamilanto-374609233/L)

---

### :hammer_and_wrench: Languages and Tools :

<div>
  <img src="https://github.com/devicons/devicon/blob/master/icons/java/java-original-wordmark.svg" title="Java" alt="Java" width="40" height="40"/>&nbsp;
  <img src="https://github.com/devicons/devicon/blob/master/icons/react/react-original-wordmark.svg" title="React" alt="React" width="40" height="40"/>&nbsp;
  <img src="https://github.com/devicons/devicon/blob/master/icons/linux/linux-plain.svg" title="Linux" alt="Linux" width="40" height="40"/>&nbsp;
  <img src="https://github.com/devicons/devicon/blob/master/icons/postgresql/postgresql-plain.svg" title="Postgresql" alt="Postgresql" width="40" height="40"/>&nbsp;
  <img src="https://github.com/devicons/devicon/blob/master/icons/typescript/typescript-original.svg" title="Typescript" alt="Typescript " width="40" height="40"/>&nbsp;
  <img src="https://github.com/devicons/devicon/blob/master/icons/javascript/javascript-original.svg" title="JavaScript" alt="JavaScript" width="40" height="40"/>&nbsp;
  <img src="https://github.com/devicons/devicon/blob/master/icons/nodejs/nodejs-original-wordmark.svg" title="NodeJS" alt="NodeJS" width="40" height="40"/>&nbsp;
</div>

---

### :fire: My Stats :

[![GitHub Streak](http://github-readme-streak-stats.herokuapp.com?user=miharyjoe&theme=blueberry&hide_border=true&date_format=M%20j%5B%2C%20Y%5D)](https://git.io/streak-stats)

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=miharyjoe&layout=compact&theme=vision-friendly-dark)](https://github.com/anuraghazra/github-readme-stats)

`;
  const readmeRow = readmeContent.split("\n");

  function updateIdentifier(identifier, replaceText) {
    const identifierIndex = findIdentifierIndex(readmeRow, identifier);
    if (!readmeRow[identifierIndex]) return;
    readmeRow[identifierIndex] = readmeRow[identifierIndex].replace(
      `<#${identifier}>`,
      replaceText
    );
  }

  const identifierToUpdate = {
    today_date: getTodayDate(),
    quote_of_the_day: getQuoteOfTheDay(),
  };

  Object.entries(identifierToUpdate).forEach(([key, value]) => {
    updateIdentifier(key, value);
  });

  return readmeRow.join("\n");
}

function getTodayDate() {
  return today.toDateString();
}

function getQuoteOfTheDay() {
  const quotes = Object.values(quote);
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}

const findIdentifierIndex = (rows, identifier) =>
  rows.findIndex((r) => Boolean(r.match(new RegExp(`<#${identifier}>`, "i"))));

const updateREADMEFile = (text) =>
  fs.writeFile("./README.md", text, () => console.log(text));

function main() {
  const newREADME = generateNewREADME();
  console.log(newREADME);
  updateREADMEFile(newREADME);
}
main();
